<a href="https://colab.research.google.com/github/DrumDong/Donggyu/blob/master/ML_lab_06_1(Softmax_Class_%EA%B5%AC%ED%98%84).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],
          [4,1,5,5],[1,7,5,5],[1,2,5,6],
          [1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]  # One-Hot Encoding

In [0]:
X = tf.placeholder('float',[None,4])
Y = tf.placeholder('float',[None,3])

nb_classes =3

W = tf.Variable(tf.random_normal([4,nb_classes]),name='weight')
b = tf.Variable(tf.random_normal([nb_classes]),name='bias')

# tf.nn softmax computes softmax activations
- softmax = exp(Logits) / reduce_sum(exp(Logits),dim)

In [0]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

# Cross entropy cost/loss

In [0]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), axis =1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Launch Graph

In [0]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  for step in range(2001):
    sess.run(optimizer,feed_dict={X:x_data,Y:y_data})
    if step % 200 ==0:
      print(step,sess.run(cost,feed_dict={X:x_data,Y:y_data}))

0 3.2737303
200 0.54859036
400 0.44774607
600 0.35428533
800 0.26578674
1000 0.22835255
1200 0.20762902
1400 0.19025588
1600 0.17547911
1800 0.16276139
2000 0.15170532


## Test& One-hot encoding

In [0]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

# Testing & One-hot encoding
  a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
  print(a, sess.run(tf.argmax(a, 1)))

[[6.7958605e-10 1.1102676e-07 9.9999988e-01]] [2]


In [0]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  
  All = sess.run(hypothesis,feed_dict={X:[[1,11,7,9],
                                         [1,2,3,4],
                                         [1,1,0,1]]})
  print(All,sess.run(tf.arg_max(All,1)))

[[5.6509176e-15 9.9997199e-01 2.8070634e-05]
 [6.0478847e-06 8.1023979e-01 1.8975408e-01]
 [7.4846707e-03 2.8382918e-01 7.0868611e-01]] [1 1 2]
