<a href="https://colab.research.google.com/github/DrumDong/Donggyu/blob/master/lab_07_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

# Training and Test datasets

In [0]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]


In [0]:
X = tf.placeholder('float',[None,3])
Y = tf.placeholder('float',[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model

In [0]:
prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

# Launch graph

In [16]:
with tf.Session() as sess:
  # Initialize Tensorflow variables
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                feed_dict={X: x_data,Y:y_data})
    #print(step,cost_val,W_val)

  #predict
  print('Prediction:', sess.run(prediction,feed_dict={X:x_test}))
  #Calculate the accuracy
  print('Accuracy:',sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))


Prediction: [2 2 2]
Accuracy: 1.0


# Big learning rate

In [20]:
X = tf.placeholder('float',[None,3])
Y = tf.placeholder('float',[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=10.0).minimize(cost)

prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

with tf.Session() as sess:
  # Initialize Tensorflow variables
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                feed_dict={X: x_data,Y:y_data})
    print(step,cost_val,W_val)

  #predict
  print('Prediction:', sess.run(prediction,feed_dict={X:x_test}))
  #Calculate the accuracy
  print('Accuracy:',sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))


0 4.0569887 [[ -6.866671    3.3318703   3.8596716]
 [-25.514307   16.091656    9.070064 ]
 [-25.100964   19.736612    7.86227  ]]
1 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
2 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
3 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
15 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
16 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
17 nan [[nan nan nan]
 [nan nan

학습을 하다가 숫자가 나와야하는데 nan값이 나오면?? -> 
- 발산하는 것일수도 있음. 학습률이 너무 큰 것인지 의심해 봐야함

# Small learning rate

In [22]:
X = tf.placeholder('float',[None,3])
Y = tf.placeholder('float',[None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis,1)
is_correct = tf.equal(prediction,tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct,tf.float32))

with tf.Session() as sess:
  # Initialize Tensorflow variables
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                feed_dict={X: x_data,Y:y_data})
    print(step,cost_val,W_val)

  #predict
  print('Prediction:', sess.run(prediction,feed_dict={X:x_test}))
  #Calculate the accuracy
  print('Accuracy:',sess.run(accuracy,feed_dict={X:x_test,Y:y_test}))


0 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
1 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
2 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
3 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
4 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
5 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
6 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]
 [ 1.4122832   0.23027678  1.2725796 ]]
7 2.2078981 [[-1.4207739   0.14522272 -0.7956217 ]
 [-0.45261535  0.29032534 -0.5785967 ]


학습이 거의 안되고 있음.

# Non-normalized inputs NaN
- 학습률도 적절하게 한 것같은데..?
- 데이터가 normalize가 되지 않은 것.
- 큰 값들이 주어지게 되면 cost function이 한쪽 방향으로 치우치게 됨.

In [0]:
import numpy as np

In [0]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [39]:
x_data = xy[:,:-1]
y_data = xy[:,[-1]]

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32,shape=[None,4])
Y = tf.placeholder(tf.float32,shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val,hy_val,_ = sess.run(
      [cost,hypothesis,train],feed_dict={X:x_data,Y:y_data}
  )
  print(step,'Cost:',cost_val,'\nPrediction:\n',hy_val)

0 Cost: 1753474400000.0 
Prediction:
 [[ 934382.9]
 [1881827.2]
 [1480198.1]
 [1037377.8]
 [1222741.9]
 [1233041.2]
 [1130065.2]
 [1439018.4]]
1 Cost: 1.9265074e+27 
Prediction:
 [[-3.0961119e+13]
 [-6.2327907e+13]
 [-4.9031116e+13]
 [-3.4370551e+13]
 [-4.0507531e+13]
 [-4.0848478e+13]
 [-3.7439041e+13]
 [-4.7667342e+13]]
2 Cost: inf 
Prediction:
 [[1.0262480e+21]
 [2.0659424e+21]
 [1.6252023e+21]
 [1.1392582e+21]
 [1.3426767e+21]
 [1.3539777e+21]
 [1.2409674e+21]
 [1.5799983e+21]]
3 Cost: inf 
Prediction:
 [[-3.4016375e+28]
 [-6.8478451e+28]
 [-5.3869527e+28]
 [-3.7762250e+28]
 [-4.4504833e+28]
 [-4.4879421e+28]
 [-4.1133540e+28]
 [-5.2371172e+28]]
4 Cost: inf 
Prediction:
 [[1.12751848e+36]
 [2.26981032e+36]
 [1.78557793e+36]
 [1.25168066e+36]
 [1.47517245e+36]
 [1.48758877e+36]
 [1.36342652e+36]
 [1.73591297e+36]]
5 Cost: inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost: nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan

MinMaxScaler()를통해 해결

In [0]:
from sklearn.preprocessing import MinMaxScaler

In [41]:
xy= MinMaxScaler(xy)
xy

MinMaxScaler(copy=True,
             feature_range=array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02,
        8.31659973e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02,
        8.28070007e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02,
        8.24159973e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02,
        8.19239990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02,
        8.18979980e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02,
        8.20450012e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02,
        8.13669983e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02,
        8.09559998e+02]]))

In [42]:
x_data = xy[:,:-1]
y_data = xy[:,[-1]]

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32,shape=[None,4])
Y = tf.placeholder(tf.float32,shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis-Y))

#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val,hy_val,_ = sess.run(
      [cost,hypothesis,train],feed_dict={X:x_data,Y:y_data}
  )
  print(step,'Cost:',cost_val,'\nPrediction:\n',hy_val)

TypeError: ignored