In [0]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
train_data = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/데이콘/train.csv', encoding='cp949')

In [0]:
test_data =  pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/데이콘/public_test.csv', encoding='cp949')

In [0]:
train_data

id  ... smishing
0            0  ...        0
1            1  ...        0
2            2  ...        0
3            4  ...        0
4            5  ...        0
...        ...  ...      ...
295940  336373  ...        0
295941  336375  ...        0
295942  336376  ...        0
295943  336377  ...        0
295944  336378  ...        0

[295945 rows x 4 columns]

In [0]:
test_data

id year_month                                               text
0     340000    2019-01  XXX고객님! 안녕하세요? 새롭게 시작하는 한 주 행복 가득하시길 기원합니다. 지난...
1     340001    2019-01   긴급 안내  XXX은행 가락동 지점  - 헬리오XXX 기본XXX    대출이자를 ...
2     340002    2019-01  XXX 고객님 안녕하세요올해는 미세먼지가 유난인거 같습니다.엊그제 새해가 시작된거같...
3     340003    2019-01  XXX 고객님찾아온 행운을 잡으셨나요? 못잡으셨다면 이번에 다시 잡으시길 기원합니다...
4     340004    2019-01  XXX 고객님새해 복 많이 받으세요 XXX은행 코스트코 퇴직연금 담당자입니다.  고...
...      ...        ...                                                ...
1621  341621    2019-04  (광고)XXX 고객님안녕하십니까!!고객님의 소중한 업무처리를 도와드린 kb창원중앙동...
1622  341622    2019-04  고객님 항상 저희 지점을 거래해 주셔서 감사합니다  본점 서비스 설문 전화 받으시면...
1623  341623    2019-04  XXX 고객님 저희 XXX은행 XXX지점을 이용해주셔서 감사드립니다  이번주도 더 ...
1624  341624    2019-04  (광고)알림 신청하면 매일 현금 100만원! XXX부동산 리브온지금 XXX부동산 리...
1625  341625    2019-04  (광고) XXX 고객님 안녕하세요.XXX봉XXX점 XXX대리입니다. 군인연금수급권자...

[1626 rows x 3 columns]

# 데이터 줄이기

In [0]:
train_0=train_data[train_data['smishing']==0]
train_1=train_data[train_data['smishing']==1]

In [0]:
train_0=train_0.sample(n=18703)

In [0]:
# 데이터 합치기
train_mini=pd.concat([train_0,train_1])

# shuffling
train_mini=train_mini.sample(frac=1).reset_index(drop=True)

In [0]:
train_mini.head(10)

id  ... smishing
0  208829  ...        1
1  152347  ...        1
2  252436  ...        0
3  113794  ...        0
4   95953  ...        1
5  175078  ...        1
6  334061  ...        1
7    8159  ...        0
8  221050  ...        0
9  159954  ...        1

[10 rows x 4 columns]

# ward 추출

In [0]:
for i in [0,1]:
  f = open('/content/drive/My Drive/Colab Notebooks/data/데이콘/smishing_Ver2_%d.txt'%i,'a')
  for line in train_mini[train_mini['smishing']==i]['text']:
    f.write('%s\n'%(line))
  f.close()

## class 0

In [0]:
f = open('/content/drive/My Drive/Colab Notebooks/data/데이콘/smishing_Ver2_0.txt','r')
lines_0 = f.readlines()
lines_0 = [l.rstrip() for l in lines_0]
f.close()

In [0]:
text_0=' '.join(lines_0)
word_list_0 = text_0.split(' ')
sorted_word_list_0= sorted(word_list_0)
sorted_word_list_0[-1]
len(sorted_word_list_0)

872189

In [0]:
# 1000개이상 단어 출력

num=1
kk_0={}
for idx,w in enumerate(sorted_word_list_0):
    if idx == 436474:
        break
    if w == sorted_word_list_0[idx+1]:
        num +=1
    else:
        if num >= 100:
            kk_0[w]=num
        num=0

In [0]:
kk_0

{'': 38633,
 '(2017.06.08)': 199,
 '(USD등': 207,
 '(XX-XXX-XXX)': 106,
 '(ㅂ)': 110,
 '(광고)': 433,
 '(광고)XXX': 749,
 '(광고)XXX은행': 104,
 '(광고)세액공제': 214,
 '(단': 132,
 '(지방소득세': 267,
 '-': 1602,
 '.': 138,
 '10월': 280,
 '115.5만원': 271,
 '11월': 223,
 '12월': 201,
 '13.2%(지방소득세포함)': 298,
 '16.5%': 313,
 '1의': 261,
 '2017년': 321,
 '2017년도': 101,
 '2018년': 271,
 '26일부터': 281,
 '3.35.5%만': 261,
 '30만원까지': 287,
 '30일': 144,
 '3월': 207,
 '4월': 253,
 '4천만원(근로소득만': 275,
 '50%': 118,
 '55세': 271,
 '5월': 318,
 '5월의': 108,
 '5천5백만원)': 256,
 '6개월': 238,
 '6월': 261,
 '6월의': 138,
 '70%': 112,
 '700만원까지': 358,
 '75%': 123,
 '7월': 436,
 '80%': 252,
 '85%': 122,
 '8월': 105,
 '90%': 189,
 '90%까지': 360,
 '92.4만원': 259,
 '9998.95pt로': 126,
 '9월': 190,
 ':': 4161,
 'ATM에서': 180,
 'ELS': 115,
 'ELS는': 126,
 'ELS에': 126,
 'EUROSTOXX50': 126,
 'HXXXEI': 152,
 'HXXXEI가': 126,
 'HXXXEI의': 108,
 'Liiv': 295,
 'Mate에서': 172,
 'OTP발급수수료?대출금?대출이자-': 126,
 'SMS입출금통지서비스가': 131,
 'SP500': 124,
 'Star': 173,
 'VIP라운지': 119,

## Class 1

In [0]:
f = open('/content/drive/My Drive/Colab Notebooks/data/데이콘/smishing_Ver2_1.txt','r')
lines_1 = f.readlines()
lines_1 = [l.rstrip() for l in lines_1]
f.close()

text_1=' '.join(lines_1)
word_list_1 = text_1.split(' ')

sorted_word_list_1= sorted(word_list_1)
len(sorted_word_list_1)

5336270

In [0]:
# 1000개이상 나오는 단어 출력

num=1
kk_1={}
for idx,w in enumerate(sorted_word_list_1):
    if idx == 2668134:
        break
    if w == sorted_word_list_1[idx+1]:
        num +=1
    else:
        if num >= 1000:
            kk_1[w]=num
        num=0

In [0]:
kk_1

{'': 274816,
 '%': 2471,
 '(': 2451,
 '(광고)': 5417,
 '(광고)XXX': 6089,
 '(광고)한국': 1239,
 '(광고)한국XXX': 1433,
 '(내용)': 1597,
 '(원금과': 1321,
 '(이자만': 1345,
 ')': 2517,
 '-': 14255,
 '.': 2393,
 '00분': 5049,
 '00시': 4677,
 '1.': 4859,
 '1.만21세65세': 1507,
 '1.만21세이상': 1061,
 '10%내외3.20%이상의': 1155,
 '10%대로': 1015,
 '10%대의': 2749,
 '13건으로': 6661,
 '13등급까지': 1455,
 '17등급': 1461,
 '18:00': 1217,
 '1금융권': 4247,
 '1년이상': 1135,
 '1년이상(1년미만도': 3467,
 '1등급까지': 3923,
 '1번': 6137,
 '1억': 3213,
 '1억4000만원금리:': 1693,
 '1억4천만원까지': 1527,
 '1억4천만원까지(월소득의21배까지)(한도는': 1129,
 '2.': 4421,
 '2.97%자격:': 5165,
 '2.직장인사업자프리랜서주부학생': 1611,
 '20%이상의': 3117,
 '2018년': 2589,
 '21배까지': 1285,
 '250%까지': 1695,
 '2500만': 1155,
 '2500만원.금리:': 1935,
 '250417원으로': 1361,
 '280%까지(직군소득별': 1659,
 '2금융권이신분2.': 1423,
 '2배까지': 1021,
 '2분만': 1867,
 '2천': 1629,
 '3%(등급': 2947,
 '3.': 4783,
 '3.45%': 1169,
 '3.75%': 1033,
 '3.97%자격:': 2581,
 '3.최근부결자': 1991,
 '300%까지': 2021,
 '300%까지.금리:': 1043,
 '300%이내가능최근': 2083,
 '3000만': 1223,
 '3

In [0]:
print(len(kk_0))
print(len(kk_1))

533
518


In [0]:
train_set=set()

for name in kk_0:
  train_set.add(name)

for name in kk_1:
  train_set.add(name)

print(len(train_set))
train_set=list(train_set)

981


## ward 통일

In [0]:
train_mini.shape

(37406, 4)

In [0]:
train_vect = np.zeros((37406,1082))

In [0]:
for i in range(0,len(train_mini['text'])):
  for name in train_set:
    if name in train_mini['text'][i]:
      train_vect[i][train_set.index(name)]=1

# Data split

In [0]:
train_label=np.array(train_mini['smishing'])
train_label

array([1, 1, 0, ..., 1, 1, 1])

In [0]:
train_vect

array([[1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(train_vect,train_label, test_size=0.4, random_state=123)
X_val, X_test,y_val,y_test = train_test_split(X_test,y_test, test_size=0.5, random_state=123)

In [0]:
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)
print(X_test.shape)
print(y_test.shape)

(22443, 1082)
(22443,)
(7481, 1082)
(7481,)
(7482, 1082)
(7482,)


# Modeiling and Test

## Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#LogisticRegression을 이용해 학습/예측/평가 수행.
lr_clf = LogisticRegression()
lr_clf.fit(X_train,y_train)
pred = lr_clf.predict(X_test)
print('CountVectorized Logistic Regression의 예측 정확도는 {0:.3f}'.format(accuracy_score(y_test,
                                                                                   pred)))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


CountVectorized Logistic Regression의 예측 정확도는 0.999


# Submit

In [0]:
submit=pd.read_csv('/content/drive/My Drive/Colab Notebooks/data/데이콘/public_test.csv', encoding='cp949')

In [0]:
submit_vect=np.zeros((1626,1082))

In [0]:
for i in range(0,len(submit['text'])):
  for name in train_set:
    if name in submit['text'][i]:
      submit_vect[i][train_set.index(name)]=1

In [0]:
submit_pred = lr_clf.predict(submit_vect)

In [0]:
submit_pred

array([0, 0, 0, ..., 0, 0, 0])

In [0]:
submit['smishing']=submit_pred

In [0]:
submit.to_csv("/content/drive/My Drive/Colab Notebooks/data/데이콘/gyu_submit.csv", mode='w')