In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


# File Handling
‘w’
- 쓰기 모드
- 새로운 파일이 생성됨
- 동일한 이름의 파일이 이미 존재하면 기존 파일이 덮어씌워 짐

'a'
- 추가모드
- 파일 존재x -> 새로운 파일 생성
- 동일한 이름 파일 -> 마지막 부분에 내용 추가

'r'
- 읽기모드
- 파일 존재x -> FileNotFoundingError

## 파일 닫기
- 파일을 연 후에는 꼭 닫아야함.
- 프로그램 종료 -> 파일 닫힘 but ***resource*** 를 점유하게됨
- 명시적으로 닫는 것이 좋다

--------------------
### open 구문 활용
f = open('test.txt','w')

f.close()

---
### with 구문 활용
- with 구문 활용 후 자동으로 close()호출
- 명시적으로 close를 하지 않아도 됨

with open('text.txt','w') as f:

  > #some statements
   
  > pass


## 파일에 내용 쓰기
- write 함수를 통해 내용 작성 가능
- \n 포함x -> 줄 안넘아감(print랑 다름)


In [0]:
f = open('writing_test.txt','w')
f.write('first line \n')
f.write('second line \n')
f.write('third line \n')
#f.write('first line \n second line \n third line')
f.close()

## 파일에 내용 추가하기
- 'a'모드를 통해 기존 파일 끝에 내용 추가 가능

In [0]:
f = open('writing_test.txt','a')

for i in range(10):
  f.write('newly added line (%d) \n'%i)

f.close()

### 실습(1)
- 입력값으로 정수(n)을 받으며, 1부터 n까지의 정수 중에서 3개를 뽑아서 일렬로 나열하는 모든 방법과 총 경우의 수를
텍스트 파일로 출력하라

- 출력되는 방법의 순서는 무관하다.
- 입력값이 3보다 작은 수 일 때는 "3보다 크거나 같은 수를 입력해주십시오." 라는 메시지를 출력해야 한다.


In [0]:
f = open('practice.txt','w')
n = int(input())
num= 1
for i in range(1,n+1):
  for j in range(1,n+1):
    for k in range(1,n+1):
      if i != j and i !=k and j != k:
        f.write('순열 %d :'%num)
        f.write('%d,'%i)
        f.write('%d,'%j)
        f.write('%d\n'%k)
        num +=1
f.close()

1


## 원하는 경로에 파일 쓰기
잘못된 예시
- f= open('C:\User\Master\Desktop\new_file.txt','w')

옳바른 예시
- f= open('C:\\\User\\\Master\\\Desktop\\\new_file.txt','w')


## 파일 읽기
- 'r'모드로 파일을 연 후, 내용을 instance로 불러옴
- readline()
  - 한 줄을 읽고 이를 문자열로 반환
  - \n 이 등장할 때까지 읽고, 다음 readline()시 \n 이후부터 읽음

In [0]:
f = open('writing_test.txt','r')
line = f.readline()
print(line)
f.close()

first line 



- readline()
  - 모든 내용을 읽기 위해서 반복해서 readline()을 호풀해야함

In [0]:
f = open('writing_test.txt','r')
for i in range(5):
  line = f.readline()
  print(line)
f.close()

first line 

second line 

third line 

newly added line (0) 

newly added line (1) 



- readline()
   - for문을 통해 한 줄 씩 읽어 변수에 문자열 할당
   - \n까지 포함하여 읽음
   - 문자열 객체에서 사용 가능한 strip(),rstrip(),lstrip() 함수를 이용하여 좌우 공백이나 \t, \n 등을 제거할 수 있음 ex) line.strip()

---

- readline 함수로 파일 전체 읽기
  -  파일의 끝에 다다르면 line 변수에는 “” 빈 문자열이 할당
  - 빈 문자열을 불 타입으로 변환하면 False가 되며,
if 조건문에서는 bool 타입으로의 형변환이 자동으로 이루어짐

In [0]:
f = open('writing_test.txt','r')
while True:
  line = f.readline()
  if not line:
    break       # break을 하지 않으면 무한루프에 빠짐
  print(line)
f.close() 

first line 

second line 

third line 

newly added line (0) 

newly added line (1) 

newly added line (2) 

newly added line (3) 

newly added line (4) 

newly added line (5) 

newly added line (6) 

newly added line (7) 

newly added line (8) 

newly added line (9) 



In [0]:
f = open('writing_test.txt','r')
for line in f:
  print(line)
f.close()

first line 

second line 

third line 

newly added line (0) 

newly added line (1) 

newly added line (2) 

newly added line (3) 

newly added line (4) 

newly added line (5) 

newly added line (6) 

newly added line (7) 

newly added line (8) 

newly added line (9) 



---

- readlines 함수 이용하여 파일 전체 읽기
- readlines 함수는 리스트 객체를 반환하며, 객체 내 아이템들은 \n을 포함한 한 줄의 문자열들임

In [0]:
f = open('writing_test.txt','r')
print(f.readlines())
f.close()

['first line \n', 'second line \n', 'third line \n', 'newly added line (0) \n', 'newly added line (1) \n', 'newly added line (2) \n', 'newly added line (3) \n', 'newly added line (4) \n', 'newly added line (5) \n', 'newly added line (6) \n', 'newly added line (7) \n', 'newly added line (8) \n', 'newly added line (9) \n']


- 두 방식 간의 차이는?
for line in f: vs for line in f.readlines()
  > -> 같음

In [0]:
f = open('writing_test.txt','r')
for line in f:
  print(line)
f.close()

first line 

second line 

third line 

newly added line (0) 

newly added line (1) 

newly added line (2) 

newly added line (3) 

newly added line (4) 

newly added line (5) 

newly added line (6) 

newly added line (7) 

newly added line (8) 

newly added line (9) 



In [0]:
f = open('writing_test.txt','r')
for line in f.readlines():
  print(line)
f.close()

first line 

second line 

third line 

newly added line (0) 

newly added line (1) 

newly added line (2) 

newly added line (3) 

newly added line (4) 

newly added line (5) 

newly added line (6) 

newly added line (7) 

newly added line (8) 

newly added line (9) 



### readlines의 활용 예
-  리스트 객체로 한 번에 불러온 뒤에, for문을 이용한 list comprehension으로 간결한 코드로 문자열을 가공할 수 있음
- interactive 모드인 Python 콘솔에서 한 줄로 입력할 때에 유용함

In [0]:
f = open('writing_test.txt','r')
lines = f.readlines()
lines = [l.rstrip() for l in lines]
print(lines) # \n이 사라짐

['first line', 'second line', 'third line', 'newly added line (0)', 'newly added line (1)', 'newly added line (2)', 'newly added line (3)', 'newly added line (4)', 'newly added line (5)', 'newly added line (6)', 'newly added line (7)', 'newly added line (8)', 'newly added line (9)']


## read 함수 이용하여 파일 전체 읽기
- \n을 포함한 전체 내용을 읽어 ***한 문자열 객체***로 반환함
- read 함수에 정수 argument를 입력함으로써 읽을 문자열 수를 조절할 수 있음



In [0]:
f = open('writing_test.txt','r')
print(f.read(20))
f.close()

first line 
second l


## 파일 존재 여부 확인하기
- os.path 모듈 내의 isfile 함수 활용
- isfile 함수는 불 자료형을 반환함

## 실습(2)
- 여러 줄로 구분된 텍스트 파일을 읽고 하나의 줄로 이어 붙여서 출력하라.
- 파일은 e-class에서 다운로드 할 것 (장범준, ‘흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야‘)

In [0]:
#1
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/jang_flower.txt','r')
with open('lyrics_one_sentence.txt','w') as w:
  for l in f.readlines():
    w.write(l.rstrip())
f.close()

#2
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/jang_flower.txt','r')
with open('lyrics_one_sentence.txt','w') as w:
  for line in f:
    w.write(line.rstrip())
f.close()

#3
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/jang_flower.txt','r')
with open('lyrics_one_sentence.txt','w') as w:
  while True:
    line = f.readline()
    if not line:
      break
    w.write(line.rstrip())
f.close()

## 실습(3)
- 텍스트 파일을 읽고 특정 단어가 등장하는 문장만 새로운 텍스트 파일로 출력하라.
- 파일은 e-class에서 다운로드 할 것 (장범준, ‘흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야‘)

In [0]:
#1
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/jang_flower.txt','r')
with open('lyrics_result.txt','w') as w:
  word = input()
  for line in f.readlines():
    if word in line:
      w.write(line)
f.close()

#2
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/jang_flower.txt','r')
with open('lyrics_result.txt','w') as w:
  word = input()
  for line in f:
    if word in line:
      w.write(line)

#3
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/jang_flower.txt','r')
with open('lyrics_result.txt','w') as w:
  word = input()
  while True:
    line = f.readline()
    if not line:
      break
    if word in line:
      w.write(line)

5
5
5


## 실습(4)
- 텍스트 파일을 읽고 주어진 단어들이 등장하는 횟수를 출력하고, 등장횟수들의 평균을 출력하라
- 파일은 e-class에서 다운로드 할 것 (Wham, ‘Last Christmas‘)


In [0]:
f = open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/last_christmas.txt', encoding='UTF8')
words_list = ['Christmas', 'give', 'heart']
sum_count = 0
each_count = [0, 0 ,0]
with open('christmas_count.txt', 'w') as w:
  for line in f:
    for i in range(len(words_list)):
      if words_list[i] in line:
        each_count[i]+=1
        sum_count+=1
  for i in range(len(words_list)):
    w.write('%s : %d\n'%(words_list[i],each_count[i]))
  w.write('Average: %d'%sum_count)

## count_each_letter

# Modules and Packages

## 모듈 (Module)
- 정의
  - (관련성이 깊은) 함수나 변수 또는 클래스들을 모아 놓은 파일
  - **.py 확장자를 갖는 일반적인 하나의 Python 파일**

- 여러 모듈로 구성된 프로그램
  - 여러 모듈로 프로그램을 구성하는 것이 강제되는 것은 아님
  - 복잡한 프로그램의 경우, 하나의 모듈에 모든 코드를 작성하기보다는 여러 모듈에 나누어 작성하는 것이 관리에 이점이 있음
  - 특정 모듈에 작성되어 있는 클래스, 함수, 변수 등을 다른 모듈에서 불러와서 사용 가능



## 모듈 자체를 불러오기
- import 모듈명 : import dogs

## 모듈 내에 특정 식별자들을 불러오기
  - from 모듈명 import 식별자1,식별자2..
  - 이런식으로 불러오면 dogs.Dog(...) 안해도됨 -> Dog(...)로 가능

## 모듈 내에 모든 식별자들을 불러오기
- from 모듈명 import *
- 위에도 모듈명을 접두어로 사용안해도됨

## Import 문법 정리
- 부적절한 문법
  - import 모듈명.식별자 X
  - dogs.py 모듈 내에 선언된 Dog 클래스를 한번에 import X
- 정리
  - from 없이 import만 사용된 경우에는 import 뒤에 모듈명이 와야함.
  - 모듈내에 선언된 식별자에 접근하기 위해서는 'from 모듈명'이 있어여함
    - import dogs.Dog (x)
    - from dogs import Dog (o)
  

## Module Import 시 주의할 점
- 식별자 중복
  - 모듈 import에서만 나타나는 문제는 아니며, 한 모듈 내에서 동일한 식별자를 여러 번 사용한 경우에도 마지막에 실행된 문장만이
효력이 있게 됨

## 패키지
- dot (.)을 이용하여 Python 모듈을 계층적으로 관리할 수 있게 해주는 도구
- Python 모듈들이 들어있는 디렉토리
- 많은 파일들을 관리할 때에 관련성이 큰 것들끼리 서브 디렉토리에 모아 놓듯이, Python 모듈들도 계층화하여 관리할 수 있음

# Set

## Set
- 중괄호 기호 {} 사용
  - a_set ={item1,item2..}
  - 여러가지 값들이 아이템으로 공존가능
  - 빈 {}을 사용할 경우 set(집합자료형) x,dictionary 자료형이 된다. 
-set() 함수 사용
  - 대입안한 빈 set(집합 자료형) 생성 가능
  - List, tuple, string 등의 시퀀스 데이터 타입을 대입
  - 시퀀스 데이터 타입 내 각 아이템들이 집합 자료형의 아이템으로 포함됨

In [0]:
print(type(set()))
str_obj ='apple'
print(set(str_obj)) # 중복은 생략되는 것을 알아두자.

<class 'set'>
{'a', 'p', 'l', 'e'}


- 다른 시퀀스 자료형으로 변환
  - list,tuple,str(set())로 사용해서 변환 가능

## Set(집합 자료형)의 특성
- mutable 타입
  - List 자료형과 동일
  - Tuple,string 자료형은 immutable 타입
- List 자료형과의 차이점
  - 중복 아이템 제거, 유니크한 아이템만 남음
    - hash value를 통해 아이템 판별
    - hash object만 set의 아이템이 됨.
  - 순서 지정 x
    - for loop 사용가능, 하지만 순서 일정x
    - Indexing, Slicing 사용 x
    

## Hashing
- Hash function
  - 임의의 길이의 데이터를 고정된 길이의 데이터로
맵핑하는 함수
  - 데이터베이스에서 검색의 속도를 높여줌
- Hash value
  - Hash function에 의한 반환 값
  - **동일한 key는 같은 hash value이지만 hash value가 같다고 동일한 key는 아님**
- 객체의 값에 특정한 int 값 부여
  - 한번 실행은 int값 유지, but 새롭게 실행시, 부여되는 int값 변화 가능
- hash()
  - 객체의 class에 정의되어 있는 
  \__hash\__(self) 함수를 호출

In [0]:
a = (1,3,5)
b = 320
print(hash(a))
print(a.__hash__())
print(hash(b))
print(b.__hash__())

2528501712789647984
2528501712789647984
320
320


## hash() vs id()
- id()
  - 객체의 identity
  - **동일한 값이여도 다른 id 갖는 경우가 있음**
  - **같은 id이면 무조건 같은 값**
- hash()
  - hash function()으로 맵핑한 정수 값 반환
  - **동일한 값은 반드시 같은 hash value**
  - **같은 hash value여도 같은 값 아닐 수 있음**
- **값의 unique를 확인하는데는 hash가 더 효율적**
  - id는 다르더라도 다 체크
  -hash value는 같은 것 만 체크

---
- immutable 타입
  - 숫자,string,tuple 등
  - hashable 타입
- mutable 타입
  - set,list,dictionary
  - 객체의 값이 바뀌면 hash value는 바껴야하기 떄문에 unhashable 타입임.
    - 집합 객체(set)의 아이템으로 포함 x

## 실습
다음 리스트에서 중복된 숫자들을 제거하라

a =[1,2,3,3,3,4,5,7,7]

1. 집합 자료형을 사용하지 않고 리스트에서 중복된 숫자를 제거한 후 결과를 리스트 형태로 출력

2. 집합 자료형을 사용하여 리스트에서 중복된 숫자를 제거

In [0]:
#1
a =[1,2,3,3,3,4,5,7,7]

lst =[]
for i in range(len(a)):
  if a[i] not in lst:
    lst.append(a[i])

lst

[1, 2, 3, 4, 5, 7]

In [0]:
#2
a =[1,2,3,3,3,4,5,7,7]
a=set(a)
a=list(a)
a

[1, 2, 3, 4, 5, 7]

## 아이템 추가 및 삭제
- 아이템 추가
  - add(item)을 통해 추가 가능
  - 객체 자체를 수정하는 방식

In [0]:
s={1,2,3,4,5}
print(id(s))
s.add(8)
print(s)
print(id(s))0

140530208868168
{1, 2, 3, 4, 5, 8}
140530208868168


- 아이템 삭제
  - remove(item) 사용, 아이템 존재 x -> Error
  - discard(item)사용, 아이템 존재 x-> 에러발생 x

In [0]:
print(s)
s.remove(8)
print(s)

{1, 2, 3, 4, 5, 8}
{1, 2, 3, 4, 5}


- 여러 아이템을 한번에 추가
  - update(item) 사용
  - 객체 자체 수정

In [0]:
print(s)
s.update([100,200,300])
print(s)

{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 100, 200, 300}


In [0]:
s.update(('a',30))
print(s)

{1, 2, 3, 4, 5, 100, 'a', 200, 300, 30}


In [0]:
s.update('python')
print(s)

{1, 2, 3, 4, 5, 100, 'a', 200, 'y', 't', 300, 'p', 'o', 'h', 'n', 30}


- 모든 아이템을 삭제
  - clear() 사용

In [0]:
print(s)
s.clear()
print(s)

{1, 2, 3, 4, 5, 100, 'a', 200, 'y', 't', 300, 'p', 'o', 'h', 'n', 30}
set()


## 집합 간 비교 및 연산
- 집합간 비교
  - issubset, issuperset 활용

In [0]:
a = {1,2,3,4,5,6}
b= {1,3,5}
print(a.issubset(b))
print(b.issubset(a))
print(a.issuperset(b))
print(b.issuperset(a))

False
True
True
False


In [0]:
a ={1,2,3}
b= {1,2,3}
print(a.issubset(b))
print(b.issubset(a))
print(a.issuperset(b))
print(b.issuperset(a))

True
True
True
True


- ==, !=,>=,<=,>,< 연산자 활용
  - ==,!= : equality 체크
  - \>,<,>=,<=: subset,superset 체크

In [0]:
a = {1,2,3,4,5,6}
b= {1,3,5}
print(a>b)
print(a<b)

True
False


- 교집합
  - intersection 메서드, 또는 & 연산자 활용

In [0]:
a = {1,2,3,4,5,6}
b= {1,3,5}
c = a.intersection(b)
d = a&b
print(c)
print(d)

{1, 3, 5}
{1, 3, 5}


- 합집합
  - union 또는  | 활용

In [0]:
a = {1,2,3,4,5,6}
b = {1,5,9}
c = a.union(b)
d = a | b
print(c)
print(d) 

{1, 2, 3, 4, 5, 6, 9}
{1, 2, 3, 4, 5, 6, 9}


- 차집합
  - difference, 또는 - 연산자 활용

In [0]:
a = {1,2,3,4,5,6}
b = {1,5,9}
c= a.difference(b)
d = b-a
print(c)
print(d)

{2, 3, 4, 6}
{9}


- len(),min(),max(),sum()
  - list와 같이 동일하게 사용 가능
- in, not in 연산
- for 문에 활용
  - **순서 일정 x**


In [0]:
a ={10,30,20,50,70,90,100}
for item in a:
  print(item)

100
70
10
50
20
90
30


## 실습

다음의 값들을 아이템으로 갖는 두 리스트 객체를 생성
- 10,20,30,40,30,20,10
- 100이하 0 이상의 모든 짝수 정수

In [0]:
lst1 = [10,20,30,40,30,20,10]
lst2 = list(range(0,101,2)) # [i for i in range(0,101,2)]

두 객체를 집합 자료형으로 변환하여 합집합, 교집합 객체를 구하고, 각각을 오름차순 정렬로 출력할 것

In [0]:
set1 = set(lst1)
set2 = set(lst2)

set_union = set1 | set2
set_intersection = set1.intersection(set2)

sorted(set_intersection) # set_union.sort()를 하려면 리스트로 바꿔줘야함 ★

[10, 20, 30, 40]

# Dictionary 데이터 타입
- key/value 쌍들을 포함하는 자료형으로서, key를 통해 value에 접근하는 데에 특화된 자료 구조
- {} 중괄호 기호와 콜론 (:)을 사용
- Key, value로 여러가지 자료형이 공존할 수 있음

In [0]:
dict_var={1:'hello','drum':'dong',(1,2):[1,2,3]}
dict_var # key 값에는 unhashable 타입(리스트,딕셔너리,set) x

{(1, 2): [1, 2, 3], 1: 'hello', 'drum': 'dong'}

- dict() 함수 사용
  - dict(key1=value1, key2=value2, …, keyN=valueN)
  - {} 와는 다르게, key값에 ''없어도 저절로 문자열로 받음
  - 문자열이 아닌 자료형은 key값에 들어올 수 없음

In [0]:
dict_var2 = dict('key1'='hello',dong='hi',num=4)
print(dict_var2) # key값에 아예 ''나 ""을 쓰면 안되는 것 같음

SyntaxError: ignored

In [0]:
dict_var2 = dict(key1='hello',dong='hi',num=4)
print(dict_var2) 

{'key1': 'hello', 'dong': 'hi', 'num': 4}


- Mutable 타입
  - 객체를 수정할 수 있음
- Key
  - List에서의 인덱스와 유사한 역할 수행
  - Key의 순서가 지정되지 않음
  - Hashable 타입이 key로 사용 가능
  - Dictionary 생성 시, 고유한 key만 남겨짐
- value
 - unhashable 타입도 모두 사용 가능
 - 고유하지 않은 값들도 모두 보존
 - value 순서도 역시 지정 x

## key를 이용한 Value 접근
- List에서의 인덱스와 같이 키를 사용함
 - dict_name[key]
 - 키가 존재하지 않으면 에러 발생

In [0]:
dict_var={'name':'donggyu','age':26,'job':'data_scientist'}
print(dict_var['name'])
print(dict_var['age'])

donggyu
26


- 기존 key에 대해서 value 변경

In [0]:
dict_var['age']=25
print(dict_var)

{'name': 'donggyu', 'age': 25, 'job': 'data_scientist'}


- 새로운 key/value 쌍을 추가 (key가 존재하지 않을 경우)

In [0]:
dict_var['phone']='01075429928'
print(dict_var)

{'name': 'donggyu', 'age': 25, 'job': 'data_scientist', 'phone': '01075429928'}


## Methods of Dictionary
- get(key,[default])
 - key에 대응하는 value 반환
 - key가 존재하지 않으면 None 발생
 - key와 함께 default에 값을 넣으면 None 대신 그 값이 반환됨
 -default 값은 생략 가능

In [0]:
print(dict_var)
print(dict_var.get('name'))
print(dict_var.get('something'))
print(dict_var.get('something','there is nothing'))

{'name': 'donggyu', 'age': 25, 'job': 'data_scientist', 'phone': '01075429928'}
donggyu
None
there is nothing


- pop(key)
  - key에 대응되는 value를 반환함
  - 해당 key/value 쌍을 객체에서 삭제
  - key가 존재하지 않을 시, error 발생

In [0]:
print(dict_var)
print(dict_var.pop('name'))
print(dict_var.pop('something'))

{'name': 'donggyu', 'age': 25, 'job': 'data_scientist', 'phone': '01075429928'}
donggyu


KeyError: ignored

- keys()
  - key 시퀀스 반환
  - **dict_keys 타입**

In [0]:
print(dict_var)
dict_var.keys()

{'age': 25, 'job': 'data_scientist', 'phone': '01075429928'}


dict_keys(['age', 'job', 'phone'])

- values()
  - value 시퀀스 반환
  - dict_values 타입
  

In [0]:
print(dict_var)
dict_var.values()

{'age': 25, 'job': 'data_scientist', 'phone': '01075429928'}


dict_values([25, 'data_scientist', '01075429928'])

- items()
  - (key,value) 튜플들을 포함하는 시퀀스 반환
  - dict_items 타입

In [0]:
print(dict_var)
dict_var.items()

{'age': 25, 'job': 'data_scientist', 'phone': '01075429928'}


dict_items([('age', 25), ('job', 'data_scientist'), ('phone', '01075429928')])

- **위의 반환되는 세가지 타입들은 값의 수정과 indexing
사용이 불가능하지만, for문에는 사용 가능**

In [0]:
for key in dict_var.keys():
  print(key,dict_var[key])

age 25
job data_scientist
phone 01075429928


In [0]:
for value in dict_var.values():
  print(value)

25
data_scientist
01075429928


In [0]:
for key,value in dict_var.items():
  print(key,value)

age 25
job data_scientist
phone 01075429928


-  keys() 없이 for문을 사용할 시, 자동으로 key에 대해 loop 적용

In [0]:
for key in dict_var:
  print(key,dict_var[key])

age 25
job data_scientist
phone 01075429928


- in, not in 연산자 사용
  - key, value의 존재 여부 확인


In [0]:
print(25 in dict_var.values())
print('name' in dict_var.keys())

True
False


keys() 메서드를 사용하지 않으면 자동으로 key에 대해 확인함

In [0]:
print('name' in dict_var)

False


- len 함수 사용 가능

In [0]:
len(dict_var)

3

## 실습
list_a는 지각한 학생들의 이름이고, list_b는 각 학생이 지각한 횟수이다.

- list_a = ['A', 'B', 'C', 'D', 'E']

- list_b = [1, 1, 2, 1, 3]


1) 학생의 이름을 key로 가지며, 각 학생이 지각한 횟수를 value로 갖는 dictionary를 생성하고 출력하라
({‘A’: 1, ‘B’:1, …, ‘E’:3})

2) 아래의 list를 이용하여 1)에서 생성된 dictionary를 업데이트하고 업데이트된 dictionary를 출력하라
(list_c는 수업마다 지각한 학생들이 기록된 리스트이며, 하루에 한 명씩만 지각했다고 가정한다.)

- list_c = ['A', 'C', 'E', 'F', 'G', 'B', 'A']


In [0]:
list_a = ['A', 'B', 'C', 'D', 'E']
list_b = [1, 1, 2, 1, 3]

In [0]:
dict_late={}
for i,j in zip(list_a,list_b):
  dict_late[i] =j

dict_late

{'A': 1, 'B': 1, 'C': 2, 'D': 1, 'E': 3}

In [0]:
list_c = ['A', 'C', 'E', 'F', 'G', 'B', 'A']
for i in list_c:
  if i in dict_late.keys():
    dict_late[i]+=1
  else:
    dict_late[i]=1

dict_late

{'A': 3, 'B': 2, 'C': 3, 'D': 1, 'E': 4, 'F': 1, 'G': 1}

## 실습
- 파일을 읽고 등장하는 각 단어의 등장 횟수를 셀 것
- “ “ 한 칸의 공백으로 구분하여, 하나 이상 연속으로 등장하는 글자를 단어로 정의함
- 등장 횟수가 10회 이상인 단어들에 대해서, 단어를 기준으로 오름차순 정렬하여 단어, 등장 횟수를 함께 출력


In [0]:
with open('/content/drive/My Drive/Colab Notebooks/파이썬프로그래밍/example.txt','r') as f:
  line_list=[]
  for line in f:
    line_list.append(line)
  #print(line_list)

  words= ''.join(line_list) 
  #print(words)

  word_list = words.split(' ')
  print(word_list)

word_dict={}
for word in word_list:
  if word not in word_dict:
    word_dict[word]=1
  else:
    word_dict[word]+=1

top10_dict={}
for key in word_dict.keys():
  if word_dict[key]>=10:
    top10_dict[key]= word_dict[key]

modify_dict={}
for word in sorted(top10_dict):
  modify_dict[word]= top10_dict[word]

print(modify_dict) 

['the', 'hangman', 'summoned', 'assistance,', 'and', 'with', 'help', 'tied', 'the', 'cap', 'over', "white's", 'face', 'with', 'a', 'handkerchief.\nit', 'was', 'not', 'always', 'easy', 'to', 'get', 'a', 'hangman', 'so', 'cheap,', 'as', 'i', 'have', 'already', 'indicated', 'on', 'a', 'previous', 'page.\nwe', 'have', 'here', 'the', 'direct', 'absorption', 'into', 'the', 'body', 'proper', 'of', 'foodstuffs', 'precisely', 'as', 'the', 'animal', 'takes', 'in', 'water', 'and', 'oxygen.\nhe', 'indicated', 'an', 'interest', 'in', 'writing.', 'an', 'employment', 'counselor', 'testified,', 'on', 'the', 'basis', 'of', 'a', 'general', 'aptitude', 'test', 'oswald', 'had', 'taken,\nand', 'tempted', 'him', 'to', 'take', 'to', 'fraudulent', 'insurance', 'as', 'a', 'certain', 'method', 'of', 'achieving', 'fortune.\nminimum', 'wages', 'have', 'been', 'established', 'and', 'other', 'wages', 'adjusted', 'toward', 'a', 'rising', 'standard', 'of', 'living.\nupon', 'these', 'and', 'the', 'private', 'visitatio

# Numpy
- numpy
 - 가장 필수적이고 기초가 되는 패키지로서, 대부분의 패키지가 NumPy에 대한 dependency가 존재함
 - 효율적인 연산이 가능한 다차원 array 자료형을 제공
- Scipy
 - Linear algebra, optimization, integration, statistics, signal processing 등의 모듈 제공
 - Scientific computing과 관련된 수많은 기능들을 제공
 - NumPy + SciPy만으로 MATLAB에서 제공하는 대부분의 계산 기능을 대체할 수 있음
- Pandas
 - 데이터를 가공하고 분석하기 위한 패키지
 - 컬럼 이름과 행의 index가 존재하는 엑셀의 표와 같은 자료형을 제공함
 - spreadsheets나 relational databases에서의 유연한 데이터 처리 기능들을 지원

In [0]:
import numpy as np

Numpy를 사용하는 이유
- list로만 계산하는데 한계가 존재함
- 기계학습은 주로 행렬의 연산으로 수행
- Numpy를 사용하지 않고 Python의 기본 기능들을 활용하여 위의 연산들을 수행할 수 있으나 많은 제약이 존재함

- dtype
 - 한 array 객체에는 모두 동일한 타입의 elements들이 포함됨
 - 여러 타입의 elements가 포함된 경우 자동으로 하나의
타입으로 변환됨

In [0]:
b=np.array([1,2,3.0])
b.dtype

dtype('float64')

- ndim
  - 차원 묻기

In [0]:
b.ndim

1

- shape
  - 각 차원의 크기
  -tuple 객체의 length는 ndim과 동일함

In [0]:
print(b.shape)
b=np.array([[1,2,3.0]])
print(b.shape)
print(b.ndim)

(3,)
(1, 3)
2


In [0]:
print(b.ndim)
print(len(b.shape)) # b.shape : (1,3)

2
2


- size
 - shape의 elements들을 모두 곱한 결과와 같음

In [0]:
b.size

3

- Not equal-length case

In [0]:
d = np.array([[1,2],[1,2,3]])
print(d)
print(d.shape)

[list([1, 2]) list([1, 2, 3])]
(2,)


- array 생성 후 shape를 변경하는 것보다
생성한 array의 elements를 변경하는 것이 더 효율적임


- np.identity
 - 정사각 행렬
-np.eye

In [0]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.eye(3,4,2) #행,렬 1이 시작할 위치

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

- np.arange
 - range 함수와 유사하게 동작, array 반환
 - **arguments로 float 사용가능**
- np.linspace

In [0]:
np.arange(10,20,0.5)

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [0]:
np.linspace(0,10,20) # start, finish, 간격 개수

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

- np array를 이용한 연산을 수행하면 새로운 객체가 생성됨

In [0]:
a = np.array([[1,2,3],[1,2,3]])
b=a
a=a*2
print(a)
print(b)

[[2 4 6]
 [2 4 6]]
[[1 2 3]
 [1 2 3]]


In [0]:
#실습

a=(1,2,3)
b=(-1,1,3)

#numpy 미사용
for i in range(len(a)):
  print(a[i]+b[i])

#numpy 사용
a= np.array([1,2,3])
b= np.array([-1,1,3])
a+b

0
3
6


array([0, 3, 6])

- **\*=, += 등의 복합 할당 연산자는 기존 객체를 수정함**

- numpy array는 mutable이지만, 일반적으로 연산 수행
혹은 메서드 실행 시 새로운 객체를 생성함

In [0]:
a = np.array([[2,4,6],[8,10,12]])
b=a
a*=2
print(a)
print(b)

[[ 4  8 12]
 [16 20 24]]
[[ 4  8 12]
 [16 20 24]]


- 슬라이싱을 통해 나오는 것도 array 객체로 반환됨

## 실습

In [0]:
A = np.array([range(11,17,1),range(17,23,1),range(23,29,1),range(29,35,1)])
A

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34]])

In [0]:
print('1',A[:2,3:])
print('2',A[::2])
print('3',A[:,4])
print('4',A[:,1::3])
print('5',A[::2,1::2])

1 [[14 15 16]
 [20 21 22]]
2 [[11 12 13 14 15 16]
 [23 24 25 26 27 28]]
3 [15 21 27 33]
4 [[12 15]
 [18 21]
 [24 27]
 [30 33]]
5 [[12 14 16]
 [24 26 28]]


## copy
- Slicing을 적용해 얻어진 새로운 array 객체는 기존 array
객체와 data를 공유함

In [0]:
print(A)
B =A[::2]
print()
print(B)
B[0]= -100
print(A)
print()
print(B)

[[11 12 13 14 15 16]
 [17 18 19 20 21 22]
 [23 24 25 26 27 28]
 [29 30 31 32 33 34]]

[[11 12 13 14 15 16]
 [23 24 25 26 27 28]]
[[-100 -100 -100 -100 -100 -100]
 [  17   18   19   20   21   22]
 [  23   24   25   26   27   28]
 [  29   30   31   32   33   34]]

[[-100 -100 -100 -100 -100 -100]
 [  23   24   25   26   27   28]]


- 하지만 Deep copy를 하게 되면 원래의 것에는 변화가 생기지 않음
 - c =a.copy()

## boolean indexing
 - numpy 배열도 불리언 인덱싱이 된다는 점 알아두자
 - C ==0 or C> 3 X 
 - np.logical_or(C== 0 or C==3)

## shampe manipulation
- reshape()
 - 최대 한축에 -1을 넣으면 임의의 shape로 reshape 가능
-transpose() = np.T
 - 전치행렬 만들기

- concatenate
 - 합치려는 두 행렬의 차원이 같아야함

In [0]:
a = np.array([[1,1,1],[1,1,1]])
b = np.zeros_like(a)
print(np.concatenate((a,b),axis=1))
print(np.concatenate((a,b),axis=0))

[[1 1 1 0 0 0]
 [1 1 1 0 0 0]]
[[1 1 1]
 [1 1 1]
 [0 0 0]
 [0 0 0]]


In [0]:
d = np.arange(12).reshape(3,4)
e = np.arange(16).reshape(4,4)
np.concatenate((d,e),axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])