<a href="https://colab.research.google.com/github/DrumDong/Donggyu/blob/master/%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D/Numpy_11_28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy
- 자료를 처리할땐 List보다 Array가 더 빠름. 왜냐하면 자료 크기가 정해져 있기 때문이다.
- 리스트는 원소를 모든 타입의 데이터를 넣을 수 있지만, Array는 그게 안됨(dtype=) 설정했을 때 그런 현상 발생 

In [0]:
import numpy as np

In [5]:
temp_list =[1,2,3]
np_arr =np.array(temp_list)
print(temp_list)
print(np_arr) #콤가가 없음을 알아두자

[1, 2, 3]
[1 2 3]


In [24]:
np.empty((3,3),dtype='float32') #랜덤 숫자가 나오게해줌

array([[1.9622734e-37, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00]], dtype=float32)

In [20]:
abc = np.array([1,2,3])
dd = np.zeros_like(abc)
# abc와 형태는 같은데 제로로 꺼내줘!! ones_like, empty_like 다 있음.
dd

array([0, 0, 0])

## 단위행렬
- 정사각행렬 ★

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3,4,2) # np.eye는 정사각행렬이 아닌데 단위행렬처럼 보이게 하는 것을 만들어줌

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# np.aragne()

In [0]:
print()

In [33]:
print(np.arange(0.7,10.5,2.1)) # error없이 알아서 출력 잘해줌

[0.7 2.8 4.9 7.  9.1]


In [35]:
print(np.linspace(0,1,10)) # 0과 1포함하고 10개로 쪼개줌.

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


실습


In [40]:
#1.
kk = np.array([-1,10,3,5,1,7])
print(kk.ndim,kk.shape,kk.size)

1 (6,) 6


In [41]:
#2.
kk = np.array([[4,2],[3,1]])
print(kk.ndim,kk.shape,kk.size)

2 (2, 2) 4


In [43]:
#3.
num3 =np.linspace(0,10,100)
print(num3)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [45]:
#4.
print(np.zeros_like(num3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


# 벡터 연산

In [46]:
num1 =[1,2,3]
num2= [1,2,3]
num1+num2 # 벡터간의 계산이 안됨

[1, 2, 3, 1, 2, 3]

In [47]:
num1 =np.array([1,2,3])
num2= np.array([1,2,3])
num1+ num2

array([2, 4, 6])

np array를 이용한 연산을 수행하면 새로운 객체가 생성됨.

In [51]:
# 실습1 
a  = [1,2,3]
b = [-1,1,3]

k=[]
for i in range(len(a)):
  k.append(a[i]+b[i])

print(k)

[0, 3, 6]


In [50]:
# 실습2
a = np.array([1,2,3])
b = np.array([-1,1,3])
print(a+b)
print(a-b)

[0 3 6]
[2 1 0]
